-- Inserción de áreas como roles
INSERT INTO BNSATE11_ROLES (B11_ID_ROL, B11_DESCRIPCION, B11_ESTADO) VALUES (5, 'MA-Mesa de ayuda', 'A');
INSERT INTO BNSATE11_ROLES (B11_ID_ROL, B11_DESCRIPCION, B11_ESTADO) VALUES (6, 'RA-Red de agencias', 'A');
INSERT INTO BNSATE11_ROLES (B11_ID_ROL, B11_DESCRIPCION, B11_ESTADO) VALUES (7, 'PF-Prevención del fraude', 'A');
INSERT INTO BNSATE11_ROLES (B11_ID_ROL, B11_DESCRIPCION, B11_ESTADO) VALUES (8, 'SO-Soporte Operativo', 'A');

