-- Mesa de ayuda (ID de rol asumido: 5)
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (77, 5, 'X', 'BLOQUEO POR ROBO'); -- Bloqueo X para Mesa de ayuda
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (78, 5, 'E', 'BLOQUEO POR PERDIDA'); -- Bloqueo E para Mesa de ayuda

-- Red de agencias (ID de rol asumido: 6)
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (79, 6, 'X', 'BLOQUEO POR ROBO'); -- Bloqueo X para Red de agencias
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (80, 6, 'E', 'BLOQUEO POR PERDIDA'); -- Bloqueo E para Red de agencias

-- Prevención del fraude (ID de rol asumido: 7)
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (81, 7, 'T', 'BLOQUEO POR ALERTA'); -- Bloqueo T para Prevención del fraude
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (82, 7, 'F', 'BLOQUEO POR FRAUDE'); -- Bloqueo F para Prevención del fraude
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (83, 7, 'N', 'DESBLOQUEAR'); -- Desbloquear

-- Soporte Operativo (ID de rol asumido: 8)
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (84, 8, 'Q', 'BLOQUEO POR MAL REALCE'); -- Bloqueo Q para Soporte Operativo
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (85, 8, 'W', 'BLOQUEO CANCELACION DE TARJETA'); -- Bloqueo W para Soporte Operativo
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (86, 8, 'L', 'BLOQUEO POR FALLECIMIENTO'); -- Bloqueos adicionales para Soporte Operativo
INSERT INTO BNSATE10_PER_PERMISOS (B10_ID_PER, B11_ID_ROL, B10_COD_FUNCIONALIDAD, B10_DESCRIPCION)
VALUES (87, 8, 'Z', 'BLOQUEO ADMINISTRATIVO'); -- Bloqueos adicionales para Soporte Operativo

