-- Crear la tabla BNMODCB20_LOG_EECC con una clave primaria compuesta
CREATE TABLE BNSATE20_LOG_BLOQUEO (
    B20_FECHA        DATE NOT NULL,
    B20_HORA         VARCHAR2(8) NOT NULL,
    B20_USUARIO      VARCHAR2(100) NOT NULL,
    B20_ACCION       VARCHAR2(50) NOT NULL,
    B20_DNI          VARCHAR2(20) NOT NULL,
    B20_COD_AGENCIA  VARCHAR2(255) DEFAULT '----' NOT NULL,
    B20_NAME_AGENCIA VARCHAR2(255) DEFAULT '---- ----- -----' NOT NULL,
    PRIMARY KEY (B20_FECHA, B20_HORA, B20_USUARIO)
);

-- Crear índices adicionales para búsquedas rápidas
CREATE INDEX BNSATE20_DNI_LOG ON BNSATE20_LOG_BLOQUEO (B20_DNI);
CREATE INDEX BNSATE20_COD_AGENCIA ON BNSATE20_LOG_BLOQUEO (B20_COD_AGENCIA);
